version: "3"
services:
  go:
    container_name: GO-TEST
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/go/src/backend
    # working_dir: /go/src/backend
    environment:
      TZ: Asia/Tokyo
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
      - 2345:2345
    depends_on:
      - "mysql"
    # security_opt:
    #   - apparmor:unconfined
    # cap_add:
    #   - SYS_PTRACE

  mysql:
    container_name: MYSQL-TEST
    build: ./mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
    ports:
      - 13306:3306
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
